themosis:
  restart: always
  image: vyygir/themosis-framework
  ports:
    - 80:80
  expose:
    - "80"
  links:
    - db
  volumes:
    - .:/var/www/project
  environment:
    HOSTNAME: local
    VIRTUALHOST: themosis.localhost
db:
  restart: always
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=themosis
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
  expose:
    - "3306"
  ports:
    - 3306:3306