version: '3'
services:
  themosis:
    restart: unless-stopped
    image: vyygir/themosis-framework
    ports:
      - 80:80
    expose:
      - "80"
    links:
      - db
    volumes:
      - .:/var/www/project
    environment:
      HOSTNAME: local
      VIRTUALHOST: themosis.localhost
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=themosis
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    expose:
      - "3306"
    ports:
      - 3306:3306